// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViandasUtn.Context;

#nullable disable

namespace ViandasUtn.Migrations
{
    [DbContext(typeof(ViandaApiContext))]
    partial class ViandaApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("ViandasUtn.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mika",
                            LastName = "Ben",
                            Password = "@Rosario22",
                            Email = "mikaben@gmail.com",
                            UserName = "benka"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dom",
                            LastName = "Toreto",
                            Password = "#Dodge1970",
                            Email = "toreto@gmail.com",
                            UserName = "toretodom"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
